Dent/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework import urls
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from api.views import paymentno, paymentok

urlpatterns = [
    path("", include("shop.urls", namespace="shop")),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("v1/", include("rest_framework.urls"), name="reset"),
    path("api/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("course/", include("commoncourse.urls", namespace="common_course")),
    path("api/", include("api.urls", namespace="api")),
    path("admin/", admin.site.urls),
    path("", include("partial.urls", namespace="partial")),
    path("location/", include("location.urls", namespace="location")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("clinic/", include("clinic.urls", namespace="clinic")),
    path("", include("doctor.urls", namespace="doctor")),
    path("account/", include("account.urls", namespace="account")),
    path("", include("reservation.urls", namespace="reserve")),
    path("", include("blog.urls", namespace="blog")),
    path("api/", include("api.urls", namespace="api")),
    path("", include("config.urls", namespace="config")),
    path("paymentok/", paymentok.as_view(), name="payment_ok"),
    path("paymentno/", paymentno.as_view(), name="payment_no"),
]
if settings.DEBUG:
    # ADD ROOT MEDIA FILES
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

api/urls.py
from django.urls import path, include
from rest_framework import routers

from .views import (
    About_usApiView,
    AddToCart,
    CatDicListApiView,
    CategoryListApiView,
    CityListApiView,
    ClearCartItem,
    ClinicDetailApi,
    ClinicDetailApiView,
    ClinicDoctorListApiView,
    ClinicListApiView,
    ClinicLoginApiView,
    ClinicPanelView,
    ClinicRegisterApiView,
    CommonCourseApiView,
    CommonCourseDetailApi,
    CompanyList,
    ComplimentCreateView,
    ComplimentDetail,
    ComplimentListApiView,
    ContactUSApiView,
    DateListApiView,
    DeleteCartItem,
    DeleteReserve,
    DiscountListApiView,
    DoctorDictionaryDetailView,
    DoctorDictionaryListApiView,
    DoctorListApiTest,
    DoctorProfileApi,
    DoctorRetrieveView,
    ExpertiseListApiView,
    FilterListApiView,
    InsuranceLIST,
    ListCart,
    OrderCreate,
    OrderList,
    PrescriptionsLIST,
    PriceList,
    ProductDetail,
    ProductListApiView,
    ProvinceList,
    RegisterWithPhoneNumber,
    ReserveCreateView,
    SliderApiView,
    SubCategoryListAPiView,
    TimeListApiView,
    ToBank,
    UpdateUserView,
    UserProfileApiView,
    UserReferralCodeApiView,
    UserReserveList,
    UserTypeApiView,
    Verify,
    VerifyUserRegister,
    WinnerApiView,
    ZoneListApiView,
    my_django_view,
    paymentno,
    paymentok,
    DoctorCreateApiView,
    DoctorUpdateApiView,
    DoctorDeleteApiView,
    DiscountCreateApiView,DiscountDeleteView
)

app_name = "api"
router = routers.SimpleRouter()
router.register(r'doctor_create', DoctorCreateApiView)
urlpatterns = [
    path(r'', include(router.urls)),
    path("discount_delete/",DiscountDeleteView.as_view(),name="discount_delete"),
    path("discount_create/",DiscountCreateApiView.as_view(),name="discount_create"),
    # path("panel/doctor/create/", DoctorCreateApiView.as_view(), name="doctor_create"),
    path("clinic_panel/", ClinicPanelView.as_view(), name="clinic_panel"),
    # path("doctor_create/", DoctorCreateApiView, name="doctor_create"),
    path("doctor_update/", DoctorUpdateApiView.as_view(), name="doctor_update"),
    path("doctor_delete/", DoctorDeleteApiView.as_view(), name="doctor_delete"),
    path("clinic_Login/", ClinicRegisterApiView.as_view(), name="clinic_register"),
    path("user_type/", UserTypeApiView.as_view(), name="user_type"),
    path("order_create/", OrderCreate.as_view(), name="order_create"),
    # path("order_create/", OrderCreate.as_view(), name="order_create"),
    path("medical_login/", ClinicLoginApiView.as_view(), name="clinic_login"),
    path("clinic_panel/", ClinicDetailApiView.as_view(), name="clinic_panel"),
    path("prize/", WinnerApiView.as_view(), name="winner_api"),
    path(
        "referral_code/",
        UserReferralCodeApiView.as_view(),
        name="UserReferralCodeApiView",
    ),
    path("sub_category/", SubCategoryListAPiView.as_view(), name="sub_create"),
    path("discount/", DiscountListApiView.as_view(), name="all_discount"),
    path("testing/", paymentok.as_view(), name="order_create"),
    path("but/", paymentno.as_view(), name="order_create"),
    path("dict_category/", CatDicListApiView.as_view(), name="dict_category"),
    path("province_list/", ProvinceList.as_view(), name="province_list"),
    path("city_list/", CityListApiView.as_view(), name="city_list"),
    path("zone_list/", ZoneListApiView.as_view(), name="zone_list"),
    path("clinic_doctor/", ClinicDoctorListApiView.as_view(), name="clinic_doctor"),
    path("delete_cart/", DeleteCartItem.as_view(), name="DeleteCartItem"),
    path(
        "doctordictionarylist/",
        DoctorDictionaryListApiView.as_view(),
        name="doctordictionarylist",
    ),
    path(
        "doctordictionarydetail/",
        DoctorDictionaryDetailView.as_view(),
        name="doctordictionarydetail",
    ),
    path(
        "doctordictionarylist/",
        DoctorDictionaryListApiView.as_view(),
        name="doctordictionarylist",
    ),
    path(
        "doctordictionarydetail/",
        DoctorDictionaryDetailView.as_view(),
        name="doctordictionarydetail",
    ),
    path("bank/", ToBank.as_view(), name="bank"),
    path("verify/", Verify.as_view(), name="bank"),
    path("exertise/", ExpertiseListApiView.as_view(), name="Home"),
    path("time/", TimeListApiView.as_view(), name="list"),
    path("reserve/", ReserveCreateView.as_view(), name="reserve_create"),
    path("update_profile/", UpdateUserView.as_view(), name="update"),
    path("verify_user_register/", VerifyUserRegister.as_view(), name="verify"),
    path("register/", RegisterWithPhoneNumber.as_view(), name="register"),
    path("date_list/", DateListApiView.as_view(), name="date_list"),
    path("doctor_filter/", DoctorListApiTest.as_view(), name="Doctor_filter"),
    path("Prescriptions/", PrescriptionsLIST.as_view(), name="Prescriptions"),
    path("filter_list/", FilterListApiView.as_view(), name="filter_list"),
    path("slider/", SliderApiView.as_view(), name="slider"),
    path("contact_us/", ContactUSApiView.as_view(), name="contact_us"),
    path("about_us/", About_usApiView.as_view(), name="about_us"),
    path("doctorProfile/", DoctorRetrieveView.as_view(), name="doctor_detail"),
    path("insurance/", InsuranceLIST.as_view(), name="insurance_list"),
    path("company/", CompanyList.as_view(), name="company_list"),
    path("price/", PriceList.as_view(), name="price_list"),
    path("common_course/", CommonCourseApiView.as_view(), name="common_course_list"),
    path(
        "common_course_detail/",
        CommonCourseDetailApi.as_view(),
        name="common_course_detail",
    ),
    path("slider/", SliderApiView.as_view(), name="slider_list"),
    path("about_us/", About_usApiView.as_view(), name="about_us"),
    path("contact_us/", ContactUSApiView.as_view(), name="contact_us"),
    path("test/<From>/<To>/<message>", my_django_view, name="test"),
    path("get_profile/", UserProfileApiView.as_view(), name="get_pro"),
    path("clinic_list/", ClinicListApiView.as_view(), name="clinic_list"),
    path("clinic_detail/", ClinicDetailApi.as_view(), name="clinic_detail"),
    path("doctor_profile/", DoctorProfileApi.as_view(), name="doctor_profile"),
    path("reserve_list/", UserReserveList.as_view(), name="reserve_list"),
    path("product_list/", ProductListApiView.as_view(), name="product_list"),
    path("category_list/", CategoryListApiView.as_view(), name="category_list"),
    path("product_detail/", ProductDetail.as_view(), name="product_detail"),
    path("AddToCart/", AddToCart.as_view(), name="AddToCart"),
    path("ListCart/", ListCart.as_view(), name="ListCart"),
    path("ClearCartItem/", ClearCartItem.as_view(), name="ClearCartItem"),
    path(
        "compliment_create/", ComplimentCreateView.as_view(), name="Compliment_Create"
    ),
    path("compliment_detail/", ComplimentDetail.as_view(), name="Compliment_Detail"),
    path("compliment_list/", ComplimentListApiView.as_view(), name="Compliment_list"),
    path("reserve_delete/", DeleteReserve.as_view(), name="DeleteReserve"),
    path("order_list/", OrderList.as_view(), name="order_list"),
    # path("location/", ZoneListApiView.as_view(), name="location"),
]

doctor/api/urls.py
from django.urls import path

from .views import DoctorListApiView, ExpertiseList, TimeListApiView

app_name = "doctor_api"

urlpatterns = [
    path("", ExpertiseList.as_view(), name="Home"),
    path("doctor/", DoctorListApiView.as_view(), name="list"),
    path("time/", TimeListApiView.as_view(), name="time"),
]

doctor/urls.py
from django.urls import path

from .views import (
    DeleteDiscount,
    DoctorCreateView,
    DoctorDeleteView,
    DoctorDetailView,
    DoctorListView,
    DoctorUpdateView,
    ExpertiseCreateView,
    ExpertiseDelete,
    ExpertiseListView,
    ExpertiseUpdateView,
    InsuranceCreateVIew,
    InsuranceDeleteView,
    InsuranceListView,
    InsuranceUpdateView,
    Unverified_Doctor_ListView,
    VisitTimeView,
    verify_doctor,
)

app_name = "doctor"

urlpatterns = [
    path("doctor_lsit/", DoctorListView, name="list"),
    path("delete/discount/<int:discount_id>/", DeleteDiscount, name="discount_delete"),
    path("verify_doctor/<int:id>/", verify_doctor.as_view(), name="verify_doctor"),
    path(
        "unverified_doctor_list/",
        Unverified_Doctor_ListView.as_view(),
        name="unverified_doctor",
    ),
    path("docotr/<int:pk>/", DoctorDetailView.as_view(), name="detail"),
    path("doctor/create/", DoctorCreateView.as_view(), name="create"),
    path("doctor/delete/<int:pk>/", DoctorDeleteView.as_view(), name="delete"),
    path("doctor/update/<int:pk>/", DoctorUpdateView.as_view(), name="update"),
    path("expertise_add/", ExpertiseCreateView.as_view(), name="expertise_create"),
    path("expertise_list", ExpertiseListView.as_view(), name="expertise_list"),
    path(
        "expertise/update/<int:id>/",
        ExpertiseUpdateView.as_view(),
        name="expertise_update",
    ),
    path("expertise/delete/<int:pk>/", ExpertiseDelete, name="expertise_delete"),
    path("visittime/", VisitTimeView, name="visit_time"),
    path("insurance/", InsuranceListView.as_view(), name="insurance_list"),
    path("insurance/create/", InsuranceCreateVIew.as_view(), name="insurance_create"),
    path(
        "insurance/update/<int:id>/",
        InsuranceUpdateView.as_view(),
        name="insurance_update",
    ),
    path("insurance/delete/<int:id>/", InsuranceDeleteView, name="insurance_delete"),
]

doctor/api/views.py
# from rest_framework import generic
from rest_framework import generics

from utilities.respones import ErrorResponse, SuccessResponse

from ..models import Doctor, Expertise, VisitTime
from .serailizers import (
    DoctorSer,
    ExpertiseSerializer,
    TimeSerializer,
    VisitTimeSerializer,
)


class ExpertiseList(generics.ListAPIView):
    model = Expertise
    serializer_class = ExpertiseSerializer

    def get(self, request, *args, **kwargs):
        try:
            instance = Expertise.objects.all()
            serialize_data = self.get_serializer(instance, many=True).data
            return SuccessResponse(data=serialize_data).send()
        except Expertise.DoesNotExist as e:
            return ErrorResponse(message="Instance does not Found.", status=404).send()


class DoctorListApiView(generics.ListAPIView):
    def get(self, request, pk, *args, **kwargs):
        try:
            instance = Doctor.objects.filter(id=pk)
            serialize_data = DoctorSer(instance, many=True).data
            name = VisitTime.objects.filter(doctor=pk)
            date = VisitTimeSerializer(name, many=True).data
            tempe_data = {
                "doctor_list": serialize_data,
                "date_list": date,
            }
            return SuccessResponse(data=tempe_data).send()
        except Expertise.DoesNotExist as e:
            return ErrorResponse(message="Instance does not Found.", status=404).send()


class TimeListApiView(generics.ListAPIView):
    model = VisitTime
    serializer_class = TimeSerializer

    def post(self, id, doctor, request, *args, **kwargs):
        try:
            instance = VisitTime.objects.filter(doctor=doctor).filter(id=id)
            serialize_data = self.get_serializer(instance, many=True).data
            return SuccessResponse(data=serialize_data).send()
        except Expertise.DoesNotExist as e:
            return ErrorResponse(message="Instance does not Found.", status=404).send()


#
# import datetime
# from rest_framework import generics
# from rest_framework.response import Response
# from .serializers import ExpertiseSerializer, TimeSer , ExpertiseSerializer ,DoctorListSerializers,VisitTimeSerializer,TimeSer,Test
# from ..models import Expertise, Doctor, VisitTime
# from utilities.respones import SuccessResponse, ErrorResponse
#
#
# class ExpertiseListApiView(generics.ListAPIView):
#     serializer_class = ExpertiseSerializer
#     model = Expertise
#
#     def get(self, request, *args, **kwargs):
#         try:
#             instance = self.model.objects.all()
#             serialized_data = self.serializer_class(instance, many=True).data
#             return SuccessResponse(data=serialized_data).send()
#         except:
#             return ErrorResponse(message="failed").send()
#
#
# # class ExpertiseListApiView(generics.ListAPIView):
# #     queryset = Expertise.objects.all()
# #     serializer_class = ExpertiseSerializer
#
# class DoctorListApiView(generics.ListAPIView):
#
#     def get(self, request, *args, **kwargs):
#         # id=request.POST.get("pk")
#         pk=request.POST.get("id")
#         try:
#             instance = Doctor.objects.filter(id=pk)
#             serialize_data = DoctorSer(instance, many=True).data
#             name = VisitTime.objects.filter(doctor=pk)
#             date = VisitTimeSerializer(name, many=True).data
#             tempe_data = {
#                 "doctor_list": serialize_data,
#                 "date_list": date,
#             }
#             return SuccessResponse(data=tempe_data).send()
#         except Expertise.DoesNotExist as e:
#             return ErrorResponse(message='Instance does not Found.', status=404).send()
#
#
# class TimeListApiView(generics.ListAPIView):
#     def get(self, request,*args, **kwargs):
#         pk = request.POST.get("pk")
#         id = request.POST.get("id")
#
#         try:
#             my_list = []
#             instance = VisitTime.objects.filter(doctor=pk, id=id)
#             a = instance.values("start_time")
#             b = instance.values("finish_time")
#             my_list = []
#             for v in instance:
#                 a = v.start_time
#                 b = v.finish_time
#                 while True:
#                     a = a + datetime.timedelta(minutes=30)
#                     my_list.append(str(a.time().replace(hour=a.hour, minute=a.minute ,second=00))[:5])
#                     if a >= b:
#                         break
#             print(my_list)
#             ser_data = TimeSer(instance, many=True).data
#             temp_data = {
#                 "data": ser_data,
#                 "my_list": my_list
#             }
#             return Response(data=temp_data, status=201)
#         except:
#             return ErrorResponse(message='Instance does not Found.', status=404).send()

doctor/templates/doctor/doctor_detail.html
{% extends "base.html" %}
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
    <meta name="author" content="Coderthemes">

    <!-- App Favicon -->
    <link rel="shortcut icon" href="{% static 'config/images/TLOGO.png' %}">

    <!-- App title -->
    <title>دنتینو | خدمات آنلاین پزشکی</title>
    {% block header_static %}
        <!-- App CSS -->
        <link href="{% static 'config/css/bootstrap-rtl.min.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'config/css/core.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'config/css/components.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'config/css/icons.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'config/css/pages.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'config/css/menu.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'config/css/responsive.css' %}" rel="stylesheet" type="text/css"/>

        <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <script src="{% static 'config/js/modernizr.min.js' %}"></script>
    {% endblock %}

    {% block content %}

        <div class="content-page">
        <!-- Start content -->
        <div class="content">
        <div class="container">

            <div class="row">
                <div class="col-sm-12">
                    <div class="bg-picture card-box">
                        <div class="profile-info-name">
                            <img src="{{ doctor.profile.url }}"
                                 class="img-thumbnail" alt="profile-image">

                            <div class="profile-info-detail">
                                <h1 class="m-t-0 m-b-0 text-center">{{ doctor.full_name }}</h1>
                                <a class="btn btn-danger" href="{% url "doctor:delete" object.id %}">حذف</a>
                                <a class="btn btn-warning" href="{% url "doctor:update" object.id %}">ویرایش</a>
{#                                <h3 class="text-muted m-b-20">آدرس:<i>{{ clinic.address }}</i></h3>#}
                                <h3>درباره پزشک:{{ doctor.bio | safe }}</h3>
                                <h3></h3>
{#                                <h3>نوع مرکز درمانی :{{ clinic.type }}</h3>#}
                                <h3>تخصص های پزشک:</h3>
                                {% for exp in doctor.expertise.all %}
                                <p>{{ exp }}</p>
                                {% endfor %}
                                <div>
{#                                       <h3>لیست شرکت های بیمه طرف قرارداد:</h3>#}
{#                                {% for insurance in insurance_list %}#}
{#                                <p>{{ insurance.name }}</p>#}
{#                                {% endfor %}#}
{#                                <div>#}
{#                                    <h3>تصاویر کلینیک</h3>#}
{#                                    <a><img src="{{ object.image1.url }}"></a>#}
{#                                    <a><img src="{{ object.image2.url }}"></a>#}
{#                                    <a><img src="{{ object.image3.url }}"></a>#}
{#                                </div>#}
{#<br>#}
<br>
<br>
<br>
<br>
<br>
<br>
{#                                <div class="button-list m-t-20">#}
{#                                    <a href="{{ object.instagram }}" type="button" class="btn btn-facebook btn-sm waves-effect waves-light">#}
{#                                        اینستاگرام کلینیک<i class="fa fa-instagram"></i>#}
{#                                    </a>#}

                                </div>
                            </div>
                        <br>
                          <h3 class="header-title m-t-0 m-b-30 text-center">لیست نوبت ها رزرو شده</h3>

                                    <div class="table-responsive">
                                        <table class="table">
                                            <thead>
                                            <tr>
                                                <th>#</th>
                                                <th>نام</th>
                                                <th>نام خانوادگی</th>
                                                <th>شماره تلفن</th>
{#                                                <th>دکتر</th>#}
                                                <th>مرکز درمانی</th>
                                                <th>تاریح ثبت</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            {% for  doctor_reserve in object.reserve.all %}
                                                <tr>
                                                    <td>{{ forloop.counter }}</td>
                                                    <td>{{ doctor_reserve.name }}</td>
                                                    <td>{{ doctor_reserve.family }}</td>
                                                    <td>{{ doctor_reserve.phone_number }}</td>
{#                                                    <td>{{ clinic_reserve.doctor }}</td>#}
                                                    <td>{{ doctor_reserve.doctor.clinic }}</td>
                                                    <td>{{ doctor_reserve.created }}</td>
                                                </tr>
                                            {% endfor %}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>

                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <!--/ meta -->



                </div>



                </div> <!-- container -->

            </div> <!-- content -->


        </div>
        <!-- End content-page -->
    {% endblock %}

    {% block js %}
        <script>
            var resizefunc = [];
        </script>

        <!-- jQuery  -->
        <script src="{% static 'config/js/jquery.min.js' %}"></script>
        <script src="{% static 'config/js/bootstrap-rtl.min.js' %}"></script>
        <script src="{% static 'config/js/detect.js' %}"></script>
        <script src="{% static 'config/js/fastclick.js' %}"></script>
        <script src="{% static 'config/js/jquery.slimscroll.js' %}"></script>
        <script src="{% static 'config/js/jquery.blockUI.js' %}"></script>
        <script src="{% static 'config/js/waves.js' %}"></script>
        <script src="{% static 'config/js/jquery.nicescroll.js' %}"></script>
        <script src="{% static 'config/js/jquery.scrollTo.min.js' %}"></script>

        <!-- App js -->
        <script src="{% static 'config/js/jquery.core.js' %}"></script>
        <script src="{% static 'config/js/jquery.app.js' %}"></script>

{#    {% for time in reserve %}#}
{#            <p>{{ time.doctor }}</p>#}
{#  {% endfor %}#}


    {% endblock %}

doctor/templates/doctor/expertise_list.html
{% extends "base.html" %}
{% load static %}
{% block header_static %}
        <!--Morris Chart CSS -->
		<link rel="stylesheet" href="{% static 'config/plugins/morris/morris.css' %}">

        <!-- App css -->
        <link href="{% static 'config/css/bootstrap-rtl.min.css' %}" rel="stylesheet" type="text/css"/>
        <link href="{% static 'config/css/core.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/components.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/icons.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/pages.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/menu.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/responsive.css' %}" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <script src="{% static 'config/js/modernizr.min.js' %}"></script>
{% endblock %}
{% block content %}
            <!-- ============================================================== -->
            <!-- Start right Content here -->
            <!-- ============================================================== -->
            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container">
<h1 class="text-center"> لیست خدمات</h1>

                        <div class="row">
                            {% for expert in object_list %}
                            <div class="col-lg-3 col-md-6">
                        		<div class="card-box">
						<img class="text-center" width="100px" height="100px" src="{{expert.image.url}}">
                        			<h2 class="text-center">{{ expert }}</h2>
                                    <a class="btn btn-danger" href="{% url "doctor:expertise_delete" expert.id %}">حذف</a>
                                    <a class="btn btn-warning" href="{% url "doctor:expertise_update" expert.id %}">ویرایش</a>
                                    </div>
                        		</div>
                            {% endfor %}
                            </div>
                        </div>
                    </div> <!-- container -->

                </div> <!-- content -->
{% endblock %}



{% block js %}
        <script>
            var resizefunc = [];
        </script>

        <!-- jQuery  -->
        <script src="{% static 'config/js/jquery.min.js' %}"></script>
        <script src="{% static 'config/js/bootstrap-rtl.min.js' %}"></script>
        <script src="{% static 'config/js/detect.js' %}"></script>
        <script src="{% static 'config/js/fastclick.js' %}"></script>
        <script src="{% static 'config/js/jquery.blockUI.js' %}"></script>
        <script src="{% static 'config/js/waves.js' %}"></script>
        <script src="{% static 'config/js/jquery.nicescroll.js' %}"></script>
        <script src="{% static 'config/js/jquery.slimscroll.js' %}"></script>
        <script src="{% static 'config/js/jquery.scrollTo.min.js' %}"></script>

        <!-- KNOB JS -->
        <!--[if IE]>
        <script type="text/javascript" src="{% static 'config/plugins/jquery-knob/excanvas.js' %}"></script>
        <![endif]-->
        <script src="{% static 'config/plugins/jquery-knob/jquery.knob.js' %}"></script>

        <!--Morris Chart-->
		<script src="{% static 'config/plugins/morris/morris.min.js' %}"></script>
		<script src="{% static 'config/plugins/raphael/raphael-min.js' %}"></script>

        <!-- Dashboard init -->
        <script src="{% static 'config/pages/jquery.dashboard.js' %}"></script>

        <!-- App js -->
        <script src="{% static 'config/js/jquery.core.js' %}"></script>
        <script src="{% static 'config/js/jquery.app.js' %}"></script>
{% endblock %}