Dent/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework import urls
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from api.views import paymentno, paymentok

urlpatterns = [
    path("", include("shop.urls", namespace="shop")),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("v1/", include("rest_framework.urls"), name="reset"),
    path("api/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("course/", include("commoncourse.urls", namespace="common_course")),
    path("api/", include("api.urls", namespace="api")),
    path("admin/", admin.site.urls),
    path("", include("partial.urls", namespace="partial")),
    path("location/", include("location.urls", namespace="location")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("clinic/", include("clinic.urls", namespace="clinic")),
    path("", include("doctor.urls", namespace="doctor")),
    path("account/", include("account.urls", namespace="account")),
    path("", include("reservation.urls", namespace="reserve")),
    path("", include("blog.urls", namespace="blog")),
    path("api/", include("api.urls", namespace="api")),
    path("", include("config.urls", namespace="config")),
    path("paymentok/", paymentok.as_view(), name="payment_ok"),
    path("paymentno/", paymentno.as_view(), name="payment_no"),
]
if settings.DEBUG:
    # ADD ROOT MEDIA FILES
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

api/urls.py
from django.urls import path, include
from rest_framework import routers

from .views import (
    About_usApiView,
    AddToCart,
    CatDicListApiView,
    CategoryListApiView,
    CityListApiView,
    ClearCartItem,
    ClinicDetailApi,
    ClinicDetailApiView,
    ClinicDoctorListApiView,
    ClinicListApiView,
    ClinicLoginApiView,
    ClinicPanelView,
    ClinicRegisterApiView,
    CommonCourseApiView,
    CommonCourseDetailApi,
    CompanyList,
    ComplimentCreateView,
    ComplimentDetail,
    ComplimentListApiView,
    ContactUSApiView,
    DateListApiView,
    DeleteCartItem,
    DeleteReserve,
    DiscountListApiView,
    DoctorDictionaryDetailView,
    DoctorDictionaryListApiView,
    DoctorListApiTest,
    DoctorProfileApi,
    DoctorRetrieveView,
    ExpertiseListApiView,
    FilterListApiView,
    InsuranceLIST,
    ListCart,
    OrderCreate,
    OrderList,
    PrescriptionsLIST,
    PriceList,
    ProductDetail,
    ProductListApiView,
    ProvinceList,
    RegisterWithPhoneNumber,
    ReserveCreateView,
    SliderApiView,
    SubCategoryListAPiView,
    TimeListApiView,
    ToBank,
    UpdateUserView,
    UserProfileApiView,
    UserReferralCodeApiView,
    UserReserveList,
    UserTypeApiView,
    Verify,
    VerifyUserRegister,
    WinnerApiView,
    ZoneListApiView,
    my_django_view,
    paymentno,
    paymentok,
    DoctorCreateApiView,
    DoctorUpdateApiView,
    DoctorDeleteApiView,
    DiscountCreateApiView,DiscountDeleteView
)

app_name = "api"
router = routers.SimpleRouter()
router.register(r'doctor_create', DoctorCreateApiView)
urlpatterns = [
    path(r'', include(router.urls)),
    path("discount_delete/",DiscountDeleteView.as_view(),name="discount_delete"),
    path("discount_create/",DiscountCreateApiView.as_view(),name="discount_create"),
    # path("panel/doctor/create/", DoctorCreateApiView.as_view(), name="doctor_create"),
    path("clinic_panel/", ClinicPanelView.as_view(), name="clinic_panel"),
    # path("doctor_create/", DoctorCreateApiView, name="doctor_create"),
    path("doctor_update/", DoctorUpdateApiView.as_view(), name="doctor_update"),
    path("doctor_delete/", DoctorDeleteApiView.as_view(), name="doctor_delete"),
    path("clinic_Login/", ClinicRegisterApiView.as_view(), name="clinic_register"),
    path("user_type/", UserTypeApiView.as_view(), name="user_type"),
    path("order_create/", OrderCreate.as_view(), name="order_create"),
    # path("order_create/", OrderCreate.as_view(), name="order_create"),
    path("medical_login/", ClinicLoginApiView.as_view(), name="clinic_login"),
    path("clinic_panel/", ClinicDetailApiView.as_view(), name="clinic_panel"),
    path("prize/", WinnerApiView.as_view(), name="winner_api"),
    path(
        "referral_code/",
        UserReferralCodeApiView.as_view(),
        name="UserReferralCodeApiView",
    ),
    path("sub_category/", SubCategoryListAPiView.as_view(), name="sub_create"),
    path("discount/", DiscountListApiView.as_view(), name="all_discount"),
    path("testing/", paymentok.as_view(), name="order_create"),
    path("but/", paymentno.as_view(), name="order_create"),
    path("dict_category/", CatDicListApiView.as_view(), name="dict_category"),
    path("province_list/", ProvinceList.as_view(), name="province_list"),
    path("city_list/", CityListApiView.as_view(), name="city_list"),
    path("zone_list/", ZoneListApiView.as_view(), name="zone_list"),
    path("clinic_doctor/", ClinicDoctorListApiView.as_view(), name="clinic_doctor"),
    path("delete_cart/", DeleteCartItem.as_view(), name="DeleteCartItem"),
    path(
        "doctordictionarylist/",
        DoctorDictionaryListApiView.as_view(),
        name="doctordictionarylist",
    ),
    path(
        "doctordictionarydetail/",
        DoctorDictionaryDetailView.as_view(),
        name="doctordictionarydetail",
    ),
    path(
        "doctordictionarylist/",
        DoctorDictionaryListApiView.as_view(),
        name="doctordictionarylist",
    ),
    path(
        "doctordictionarydetail/",
        DoctorDictionaryDetailView.as_view(),
        name="doctordictionarydetail",
    ),
    path("bank/", ToBank.as_view(), name="bank"),
    path("verify/", Verify.as_view(), name="bank"),
    path("exertise/", ExpertiseListApiView.as_view(), name="Home"),
    path("time/", TimeListApiView.as_view(), name="list"),
    path("reserve/", ReserveCreateView.as_view(), name="reserve_create"),
    path("update_profile/", UpdateUserView.as_view(), name="update"),
    path("verify_user_register/", VerifyUserRegister.as_view(), name="verify"),
    path("register/", RegisterWithPhoneNumber.as_view(), name="register"),
    path("date_list/", DateListApiView.as_view(), name="date_list"),
    path("doctor_filter/", DoctorListApiTest.as_view(), name="Doctor_filter"),
    path("Prescriptions/", PrescriptionsLIST.as_view(), name="Prescriptions"),
    path("filter_list/", FilterListApiView.as_view(), name="filter_list"),
    path("slider/", SliderApiView.as_view(), name="slider"),
    path("contact_us/", ContactUSApiView.as_view(), name="contact_us"),
    path("about_us/", About_usApiView.as_view(), name="about_us"),
    path("doctorProfile/", DoctorRetrieveView.as_view(), name="doctor_detail"),
    path("insurance/", InsuranceLIST.as_view(), name="insurance_list"),
    path("company/", CompanyList.as_view(), name="company_list"),
    path("price/", PriceList.as_view(), name="price_list"),
    path("common_course/", CommonCourseApiView.as_view(), name="common_course_list"),
    path(
        "common_course_detail/",
        CommonCourseDetailApi.as_view(),
        name="common_course_detail",
    ),
    path("slider/", SliderApiView.as_view(), name="slider_list"),
    path("about_us/", About_usApiView.as_view(), name="about_us"),
    path("contact_us/", ContactUSApiView.as_view(), name="contact_us"),
    path("test/<From>/<To>/<message>", my_django_view, name="test"),
    path("get_profile/", UserProfileApiView.as_view(), name="get_pro"),
    path("clinic_list/", ClinicListApiView.as_view(), name="clinic_list"),
    path("clinic_detail/", ClinicDetailApi.as_view(), name="clinic_detail"),
    path("doctor_profile/", DoctorProfileApi.as_view(), name="doctor_profile"),
    path("reserve_list/", UserReserveList.as_view(), name="reserve_list"),
    path("product_list/", ProductListApiView.as_view(), name="product_list"),
    path("category_list/", CategoryListApiView.as_view(), name="category_list"),
    path("product_detail/", ProductDetail.as_view(), name="product_detail"),
    path("AddToCart/", AddToCart.as_view(), name="AddToCart"),
    path("ListCart/", ListCart.as_view(), name="ListCart"),
    path("ClearCartItem/", ClearCartItem.as_view(), name="ClearCartItem"),
    path(
        "compliment_create/", ComplimentCreateView.as_view(), name="Compliment_Create"
    ),
    path("compliment_detail/", ComplimentDetail.as_view(), name="Compliment_Detail"),
    path("compliment_list/", ComplimentListApiView.as_view(), name="Compliment_list"),
    path("reserve_delete/", DeleteReserve.as_view(), name="DeleteReserve"),
    path("order_list/", OrderList.as_view(), name="order_list"),
    # path("location/", ZoneListApiView.as_view(), name="location"),
]

doctor/urls.py
from django.urls import path

from .views import (
    DeleteDiscount,
    DoctorCreateView,
    DoctorDeleteView,
    DoctorDetailView,
    DoctorListView,
    DoctorUpdateView,
    ExpertiseCreateView,
    ExpertiseDelete,
    ExpertiseListView,
    ExpertiseUpdateView,
    InsuranceCreateVIew,
    InsuranceDeleteView,
    InsuranceListView,
    InsuranceUpdateView,
    Unverified_Doctor_ListView,
    VisitTimeView,
    verify_doctor,
)

app_name = "doctor"

urlpatterns = [
    path("doctor_lsit/", DoctorListView, name="list"),
    path("delete/discount/<int:discount_id>/", DeleteDiscount, name="discount_delete"),
    path("verify_doctor/<int:id>/", verify_doctor.as_view(), name="verify_doctor"),
    path(
        "unverified_doctor_list/",
        Unverified_Doctor_ListView.as_view(),
        name="unverified_doctor",
    ),
    path("docotr/<int:pk>/", DoctorDetailView.as_view(), name="detail"),
    path("doctor/create/", DoctorCreateView.as_view(), name="create"),
    path("doctor/delete/<int:pk>/", DoctorDeleteView.as_view(), name="delete"),
    path("doctor/update/<int:pk>/", DoctorUpdateView.as_view(), name="update"),
    path("expertise_add/", ExpertiseCreateView.as_view(), name="expertise_create"),
    path("expertise_list", ExpertiseListView.as_view(), name="expertise_list"),
    path(
        "expertise/update/<int:id>/",
        ExpertiseUpdateView.as_view(),
        name="expertise_update",
    ),
    path("expertise/delete/<int:pk>/", ExpertiseDelete, name="expertise_delete"),
    path("visittime/", VisitTimeView, name="visit_time"),
    path("insurance/", InsuranceListView.as_view(), name="insurance_list"),
    path("insurance/create/", InsuranceCreateVIew.as_view(), name="insurance_create"),
    path(
        "insurance/update/<int:id>/",
        InsuranceUpdateView.as_view(),
        name="insurance_update",
    ),
    path("insurance/delete/<int:id>/", InsuranceDeleteView, name="insurance_delete"),
]

partial/urls.py
from django.urls import path

from .views import (  # InsuranceCreateVIew,; InsuranceDeleteView,; InsuranceListView,; InsuranceUpdateView,
    ComanyDeleteView,
    CompanyCreateView,
    CompanyListView,
    CompanyUpdateView,
    ComplimentListVIew,
    DoctoDictonaryUpdate,
    DoctorDictCatCrate,
    DoctorDictCatDelete,
    DoctorDictCategoryListView,
    DoctorDictCatUpdate,
    DoctorDictionaryCreate,
    DoctorDictionaryDelete,
    DoctorDictionaryList,
    PrescriptionCreate,
    PrescriptionDeleteVIew,
    PrescriptionDetailView,
    PrescriptionListView,
    PrescriptionUpdate,
    PriceCreateVIew,
    PriceDeleteView,
    PriceListView,
    PriceUpdateView,
)

app_name = "partial"
urlpatterns = (
    path("prescription/", PrescriptionListView.as_view(), name="prescription_list"),
    path("dict_list/", DoctorDictionaryList.as_view(), name="dict_list"),
    path("dict_create/", DoctorDictionaryCreate.as_view(), name="dict_create"),
    path("dict_update/<int:id>/", DoctoDictonaryUpdate.as_view(), name="dict_update"),
    path("dict_delete/<int:id>/", DoctorDictionaryDelete.as_view(), name="dict_delete"),
    path(
        "prescription/<int:id>/",
        PrescriptionDetailView.as_view(),
        name="prescription_detail",
    ),
    path(
        "prescription/create/", PrescriptionCreate.as_view(), name="prescription_create"
    ),
    path(
        "prescription/update/<int:id>/",
        PrescriptionUpdate.as_view(),
        name="prescription_update",
    ),
    path(
        "prescription/delete/<int:id>/",
        PrescriptionDeleteVIew,
        name="prescription_delete",
    ),
    path("company/", CompanyListView.as_view(), name="company_list"),
    path("company/create/", CompanyCreateView.as_view(), name="company_create"),
    path(
        "company/update/<int:id>/",
        CompanyUpdateView.as_view(),
        name="company_update",
    ),
    path("company/delete/<int:id>/", ComanyDeleteView, name="company_delete"),
    # path("insurance/", InsuranceListView.as_view(), name="insurance_list"),
    # path(
    #     "insurance/delete/<slug:slug>/",
    #     InsuranceDeleteView.as_view(),
    #     name="insurance_delete",
    # ),
    # path(
    #     "insurance/update/<slug:slug>/",
    #     InsuranceUpdateView.as_view(),
    #     name="insurance_update",
    # ),
    # path("insurance/create/", InsuranceCreateVIew.as_view(), name="insurance_create"),
    path("price/", PriceListView.as_view(), name="price_list"),
    path("price/update/<int:id>/", PriceUpdateView.as_view(), name="price_update"),
    path("price/create/", PriceCreateVIew.as_view(), name="price_create"),
    path("price/delete/<int:id>/", PriceDeleteView, name="price_delete"),
    path("compliment_list/", ComplimentListVIew.as_view(), name="compliment"),
    path("dr_dict_cat_list/", DoctorDictCategoryListView.as_view(), name="dr_cat_list"),
    path("dr_dict_cat_create/", DoctorDictCatCrate.as_view(), name="dr_cat_create"),
    path(
        "dr_dict_cat/update/<int:id>/",
        DoctorDictCatUpdate.as_view(),
        name="dr_cat_update",
    ),
    path(
        "dr_dict_cat/update/<int:id>/",
        DoctorDictCatUpdate.as_view(),
        name="dr_cat_update",
    ),
    path("dr_dict_cat/delete/<int:id>/", DoctorDictCatDelete, name="dr_cat_delete"),
)

partial/forms.py
from django import forms

from .models import (
    Company,
    DoctorDictionary,
    DoctorDictionaryCategory,
    Prescriptions,
    Price,
)


class DoctorDictCatForm(forms.ModelForm):
    class Meta:
        model = DoctorDictionaryCategory
        fields = ("name",)
        labels = {"name": "عنوان دسته بندی"}


class DoctorDictionaryForm(forms.ModelForm):
    class Meta:
        model = DoctorDictionary
        fields = ("word", "meaning", "logo", "category")
        labels = {
            "word": "لغت",
            "meaning": "معنی",
            "logo": "لوگو",
            "category": "دسته بندی",
        }


class DoctorDictCatForm(forms.ModelForm):
    class Meta:
        model = DoctorDictionaryCategory
        fields = ("name",)
        labels = {"name": "عنوان دسته بندی"}


class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = ("title", "image")
        labels = {"title": "نام مجموعه", "image": "لوگو"}


class PriceForm(forms.ModelForm):
    class Meta:
        model = Price
        fields = ("title", "price")

        labels = {"title": "عنوان", "price": "قیمت"}


class Form(forms.ModelForm):
    class Meta:
        model = Company
        fields = ("title", "image")

        labels = {"title": "نام مجموعه", "image": "لوگو"}


class PrescriptionForm(forms.ModelForm):
    class Meta:
        model = Prescriptions
        fields = (
            "title",
            "description",
            "image",
        )
        labels = {
            "title": "عنوان",
            "description": "توضیحات",
            "image": "تصویر",
        }

partial/templates/company_list.html
{% extends "base.html" %}
{% load static %}
{% block header_static %}
    <!--Morris Chart CSS -->
    <link rel="stylesheet" href="{% static 'config/plugins/morris/morris.css' %}">

    <!-- App css -->
    <link href="{% static 'config/css/bootstrap-rtl.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/core.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/components.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/icons.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/pages.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/menu.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/responsive.css' %}" rel="stylesheet" type="text/css"/>

    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="{% static 'config/js/modernizr.min.js' %}"></script>
{% endblock %}
{% block content %}
    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <h1 class="text-center"> لیست شرکت ها</h1>

                <div class="row">
                    {% for company in object_list %}
                        <div class="col-lg-3 col-md-6">
                            <div class="card-box">
                                <h2 class="text-center">{{ company.title }}</h2>
                                <a class="btn btn-warning" href="{% url "partial:company_update" company.id %}">ویرایش</a>
                                <a class="btn btn-danger" href="{% url "partial:company_delete" company.id %}">حذف</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div> <!-- container -->

    </div> <!-- content -->
{% endblock %}



{% block js %}
    <script>
        var resizefunc = [];
    </script>

    <!-- jQuery  -->
    <script src="{% static 'config/js/jquery.min.js' %}"></script>
    <script src="{% static 'config/js/bootstrap-rtl.min.js' %}"></script>
    <script src="{% static 'config/js/detect.js' %}"></script>
    <script src="{% static 'config/js/fastclick.js' %}"></script>
    <script src="{% static 'config/js/jquery.blockUI.js' %}"></script>
    <script src="{% static 'config/js/waves.js' %}"></script>
    <script src="{% static 'config/js/jquery.nicescroll.js' %}"></script>
    <script src="{% static 'config/js/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'config/js/jquery.scrollTo.min.js' %}"></script>

    <!-- KNOB JS -->
    <!--[if IE]>
        <script type="text/javascript" src="{% static 'config/plugins/jquery-knob/excanvas.js' %}"></script>
        <![endif]-->
    <script src="{% static 'config/plugins/jquery-knob/jquery.knob.js' %}"></script>

    <!--Morris Chart-->
    <script src="{% static 'config/plugins/morris/morris.min.js' %}"></script>
    <script src="{% static 'config/plugins/raphael/raphael-min.js' %}"></script>

    <!-- Dashboard init -->
    <script src="{% static 'config/pages/jquery.dashboard.js' %}"></script>

    <!-- App js -->
    <script src="{% static 'config/js/jquery.core.js' %}"></script>
    <script src="{% static 'config/js/jquery.app.js' %}"></script>
{% endblock %}

partial/templates/insurance_list.html
{% extends "base.html" %}
{% load static %}
{% block header_static %}
    <!--Morris Chart CSS -->
    <link rel="stylesheet" href="{% static 'config/plugins/morris/morris.css' %}">

    <!-- App css -->
    <link href="{% static 'config/css/bootstrap-rtl.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/core.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/components.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/icons.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/pages.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/menu.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/responsive.css' %}" rel="stylesheet" type="text/css"/>

    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="{% static 'config/js/modernizr.min.js' %}"></script>
{% endblock %}
{% block content %}
    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <h1 class="text-center"> لیست شرکت های بیمه</h1>

                <div class="row">
                    {% for insurance in object_list %}
                        <div class="col-lg-3 col-md-6">
                            <div class="card-box">
                                 <img src="{{ insurance.image.url }}"  width="100px" height="100px" class="text-center">
                                <h2 class="text-center">{{ insurance.name }}</h2>
                                <a class="btn btn-warning" href="{% url "doctor:insurance_update" insurance.id %}">ویرایش</a>
                                <a class="btn btn-danger" href="{% url "doctor:insurance_delete" insurance.id %}">حذف</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div> <!-- container -->

    </div> <!-- content -->
{% endblock %}



{% block js %}
    <script>
        var resizefunc = [];
    </script>

    <!-- jQuery  -->
    <script src="{% static 'config/js/jquery.min.js' %}"></script>
    <script src="{% static 'config/js/bootstrap-rtl.min.js' %}"></script>
    <script src="{% static 'config/js/detect.js' %}"></script>
    <script src="{% static 'config/js/fastclick.js' %}"></script>
    <script src="{% static 'config/js/jquery.blockUI.js' %}"></script>
    <script src="{% static 'config/js/waves.js' %}"></script>
    <script src="{% static 'config/js/jquery.nicescroll.js' %}"></script>
    <script src="{% static 'config/js/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'config/js/jquery.scrollTo.min.js' %}"></script>

    <!-- KNOB JS -->
    <!--[if IE]>
        <script type="text/javascript" src="{% static 'config/plugins/jquery-knob/excanvas.js' %}"></script>
        <![endif]-->
    <script src="{% static 'config/plugins/jquery-knob/jquery.knob.js' %}"></script>

    <!--Morris Chart-->
    <script src="{% static 'config/plugins/morris/morris.min.js' %}"></script>
    <script src="{% static 'config/plugins/raphael/raphael-min.js' %}"></script>

    <!-- Dashboard init -->
    <script src="{% static 'config/pages/jquery.dashboard.js' %}"></script>

    <!-- App js -->
    <script src="{% static 'config/js/jquery.core.js' %}"></script>
    <script src="{% static 'config/js/jquery.app.js' %}"></script>
{% endblock %}

partial/templates/price_list.html
{% extends "base.html" %}
{% load static %}
{% block header_static %}
    <!--Morris Chart CSS -->
    <link rel="stylesheet" href="{% static 'config/plugins/morris/morris.css' %}">

    <!-- App css -->
    <link href="{% static 'config/css/bootstrap-rtl.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/core.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/components.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/icons.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/pages.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/menu.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'config/css/responsive.css' %}" rel="stylesheet" type="text/css"/>

    <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

    <script src="{% static 'config/js/modernizr.min.js' %}"></script>
{% endblock %}
{% block content %}
    <!-- ============================================================== -->
    <!-- Start right Content here -->
    <!-- ============================================================== -->
    <div class="content-page">
        <!-- Start content -->
        <div class="content">
            <div class="container">
                <h1 class="text-center"> لیست تعرفه ها</h1>

                <div class="row">
                    {% for price in object_list %}
                        <div class="col-lg-3 col-md-6">
                            <div class="card-box">
                                <h2 class="text-center">{{ price.title }}</h2>
                                <p class="text-center">{{ price.price }}</p>
                                <a class="btn btn-warning" href="{% url "partial:price_update" price.id %}">ویرایش</a>
                                <a class="btn btn-danger" href="{% url "partial:price_delete" price.id %}">حذف</a>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div> <!-- container -->

    </div> <!-- content -->
{% endblock %}



{% block js %}
    <script>
        var resizefunc = [];
    </script>

    <!-- jQuery  -->
    <script src="{% static 'config/js/jquery.min.js' %}"></script>
    <script src="{% static 'config/js/bootstrap-rtl.min.js' %}"></script>
    <script src="{% static 'config/js/detect.js' %}"></script>
    <script src="{% static 'config/js/fastclick.js' %}"></script>
    <script src="{% static 'config/js/jquery.blockUI.js' %}"></script>
    <script src="{% static 'config/js/waves.js' %}"></script>
    <script src="{% static 'config/js/jquery.nicescroll.js' %}"></script>
    <script src="{% static 'config/js/jquery.slimscroll.js' %}"></script>
    <script src="{% static 'config/js/jquery.scrollTo.min.js' %}"></script>

    <!-- KNOB JS -->
    <!--[if IE]>
        <script type="text/javascript" src="{% static 'config/plugins/jquery-knob/excanvas.js' %}"></script>
        <![endif]-->
    <script src="{% static 'config/plugins/jquery-knob/jquery.knob.js' %}"></script>

    <!--Morris Chart-->
    <script src="{% static 'config/plugins/morris/morris.min.js' %}"></script>
    <script src="{% static 'config/plugins/raphael/raphael-min.js' %}"></script>

    <!-- Dashboard init -->
    <script src="{% static 'config/pages/jquery.dashboard.js' %}"></script>

    <!-- App js -->
    <script src="{% static 'config/js/jquery.core.js' %}"></script>
    <script src="{% static 'config/js/jquery.app.js' %}"></script>
{% endblock %}