Dent/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from rest_framework import urls
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from api.views import paymentno, paymentok

urlpatterns = [
    path("", include("shop.urls", namespace="shop")),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("v1/", include("rest_framework.urls"), name="reset"),
    path("api/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("course/", include("commoncourse.urls", namespace="common_course")),
    path("api/", include("api.urls", namespace="api")),
    path("admin/", admin.site.urls),
    path("", include("partial.urls", namespace="partial")),
    path("location/", include("location.urls", namespace="location")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
    path("clinic/", include("clinic.urls", namespace="clinic")),
    path("", include("doctor.urls", namespace="doctor")),
    path("account/", include("account.urls", namespace="account")),
    path("", include("reservation.urls", namespace="reserve")),
    path("", include("blog.urls", namespace="blog")),
    path("api/", include("api.urls", namespace="api")),
    path("", include("config.urls", namespace="config")),
    path("paymentok/", paymentok.as_view(), name="payment_ok"),
    path("paymentno/", paymentno.as_view(), name="payment_no"),
]
if settings.DEBUG:
    # ADD ROOT MEDIA FILES
    urlpatterns = urlpatterns + static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )
    urlpatterns = urlpatterns + static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT
    )

api/urls.py
from django.urls import path, include
from rest_framework import routers

from .views import (
    About_usApiView,
    AddToCart,
    CatDicListApiView,
    CategoryListApiView,
    CityListApiView,
    ClearCartItem,
    ClinicDetailApi,
    ClinicDetailApiView,
    ClinicDoctorListApiView,
    ClinicListApiView,
    ClinicLoginApiView,
    ClinicPanelView,
    ClinicRegisterApiView,
    CommonCourseApiView,
    CommonCourseDetailApi,
    CompanyList,
    ComplimentCreateView,
    ComplimentDetail,
    ComplimentListApiView,
    ContactUSApiView,
    DateListApiView,
    DeleteCartItem,
    DeleteReserve,
    DiscountListApiView,
    DoctorDictionaryDetailView,
    DoctorDictionaryListApiView,
    DoctorListApiTest,
    DoctorProfileApi,
    DoctorRetrieveView,
    ExpertiseListApiView,
    FilterListApiView,
    InsuranceLIST,
    ListCart,
    OrderCreate,
    OrderList,
    PrescriptionsLIST,
    PriceList,
    ProductDetail,
    ProductListApiView,
    ProvinceList,
    RegisterWithPhoneNumber,
    ReserveCreateView,
    SliderApiView,
    SubCategoryListAPiView,
    TimeListApiView,
    ToBank,
    UpdateUserView,
    UserProfileApiView,
    UserReferralCodeApiView,
    UserReserveList,
    UserTypeApiView,
    Verify,
    VerifyUserRegister,
    WinnerApiView,
    ZoneListApiView,
    my_django_view,
    paymentno,
    paymentok,
    DoctorCreateApiView,
    DoctorUpdateApiView,
    DoctorDeleteApiView,
    DiscountCreateApiView,DiscountDeleteView
)

app_name = "api"
router = routers.SimpleRouter()
router.register(r'doctor_create', DoctorCreateApiView)
urlpatterns = [
    path(r'', include(router.urls)),
    path("discount_delete/",DiscountDeleteView.as_view(),name="discount_delete"),
    path("discount_create/",DiscountCreateApiView.as_view(),name="discount_create"),
    # path("panel/doctor/create/", DoctorCreateApiView.as_view(), name="doctor_create"),
    path("clinic_panel/", ClinicPanelView.as_view(), name="clinic_panel"),
    # path("doctor_create/", DoctorCreateApiView, name="doctor_create"),
    path("doctor_update/", DoctorUpdateApiView.as_view(), name="doctor_update"),
    path("doctor_delete/", DoctorDeleteApiView.as_view(), name="doctor_delete"),
    path("clinic_Login/", ClinicRegisterApiView.as_view(), name="clinic_register"),
    path("user_type/", UserTypeApiView.as_view(), name="user_type"),
    path("order_create/", OrderCreate.as_view(), name="order_create"),
    # path("order_create/", OrderCreate.as_view(), name="order_create"),
    path("medical_login/", ClinicLoginApiView.as_view(), name="clinic_login"),
    path("clinic_panel/", ClinicDetailApiView.as_view(), name="clinic_panel"),
    path("prize/", WinnerApiView.as_view(), name="winner_api"),
    path(
        "referral_code/",
        UserReferralCodeApiView.as_view(),
        name="UserReferralCodeApiView",
    ),
    path("sub_category/", SubCategoryListAPiView.as_view(), name="sub_create"),
    path("discount/", DiscountListApiView.as_view(), name="all_discount"),
    path("testing/", paymentok.as_view(), name="order_create"),
    path("but/", paymentno.as_view(), name="order_create"),
    path("dict_category/", CatDicListApiView.as_view(), name="dict_category"),
    path("province_list/", ProvinceList.as_view(), name="province_list"),
    path("city_list/", CityListApiView.as_view(), name="city_list"),
    path("zone_list/", ZoneListApiView.as_view(), name="zone_list"),
    path("clinic_doctor/", ClinicDoctorListApiView.as_view(), name="clinic_doctor"),
    path("delete_cart/", DeleteCartItem.as_view(), name="DeleteCartItem"),
    path(
        "doctordictionarylist/",
        DoctorDictionaryListApiView.as_view(),
        name="doctordictionarylist",
    ),
    path(
        "doctordictionarydetail/",
        DoctorDictionaryDetailView.as_view(),
        name="doctordictionarydetail",
    ),
    path(
        "doctordictionarylist/",
        DoctorDictionaryListApiView.as_view(),
        name="doctordictionarylist",
    ),
    path(
        "doctordictionarydetail/",
        DoctorDictionaryDetailView.as_view(),
        name="doctordictionarydetail",
    ),
    path("bank/", ToBank.as_view(), name="bank"),
    path("verify/", Verify.as_view(), name="bank"),
    path("exertise/", ExpertiseListApiView.as_view(), name="Home"),
    path("time/", TimeListApiView.as_view(), name="list"),
    path("reserve/", ReserveCreateView.as_view(), name="reserve_create"),
    path("update_profile/", UpdateUserView.as_view(), name="update"),
    path("verify_user_register/", VerifyUserRegister.as_view(), name="verify"),
    path("register/", RegisterWithPhoneNumber.as_view(), name="register"),
    path("date_list/", DateListApiView.as_view(), name="date_list"),
    path("doctor_filter/", DoctorListApiTest.as_view(), name="Doctor_filter"),
    path("Prescriptions/", PrescriptionsLIST.as_view(), name="Prescriptions"),
    path("filter_list/", FilterListApiView.as_view(), name="filter_list"),
    path("slider/", SliderApiView.as_view(), name="slider"),
    path("contact_us/", ContactUSApiView.as_view(), name="contact_us"),
    path("about_us/", About_usApiView.as_view(), name="about_us"),
    path("doctorProfile/", DoctorRetrieveView.as_view(), name="doctor_detail"),
    path("insurance/", InsuranceLIST.as_view(), name="insurance_list"),
    path("company/", CompanyList.as_view(), name="company_list"),
    path("price/", PriceList.as_view(), name="price_list"),
    path("common_course/", CommonCourseApiView.as_view(), name="common_course_list"),
    path(
        "common_course_detail/",
        CommonCourseDetailApi.as_view(),
        name="common_course_detail",
    ),
    path("slider/", SliderApiView.as_view(), name="slider_list"),
    path("about_us/", About_usApiView.as_view(), name="about_us"),
    path("contact_us/", ContactUSApiView.as_view(), name="contact_us"),
    path("test/<From>/<To>/<message>", my_django_view, name="test"),
    path("get_profile/", UserProfileApiView.as_view(), name="get_pro"),
    path("clinic_list/", ClinicListApiView.as_view(), name="clinic_list"),
    path("clinic_detail/", ClinicDetailApi.as_view(), name="clinic_detail"),
    path("doctor_profile/", DoctorProfileApi.as_view(), name="doctor_profile"),
    path("reserve_list/", UserReserveList.as_view(), name="reserve_list"),
    path("product_list/", ProductListApiView.as_view(), name="product_list"),
    path("category_list/", CategoryListApiView.as_view(), name="category_list"),
    path("product_detail/", ProductDetail.as_view(), name="product_detail"),
    path("AddToCart/", AddToCart.as_view(), name="AddToCart"),
    path("ListCart/", ListCart.as_view(), name="ListCart"),
    path("ClearCartItem/", ClearCartItem.as_view(), name="ClearCartItem"),
    path(
        "compliment_create/", ComplimentCreateView.as_view(), name="Compliment_Create"
    ),
    path("compliment_detail/", ComplimentDetail.as_view(), name="Compliment_Detail"),
    path("compliment_list/", ComplimentListApiView.as_view(), name="Compliment_list"),
    path("reserve_delete/", DeleteReserve.as_view(), name="DeleteReserve"),
    path("order_list/", OrderList.as_view(), name="order_list"),
    # path("location/", ZoneListApiView.as_view(), name="location"),
]

location/urls.py
from django.urls import path

from .views import (
    CityCreateView,
    CityDeleteView,
    CityListView,
    CityUpdateView,
    ProvinceCreate,
    ProvinceDelete,
    ProvinceDetail,
    ProvinceListView,
    ProvinceUpdate,
    ZoneCreate,
    ZoneDeleteView,
    ZoneListView,
    ZoneUpdate,
)

app_name = "Location"
urlpatterns = [
    path("", ProvinceListView.as_view(), name="province"),
    path("city_list/", CityListView.as_view(), name="city_list"),
    path("city_create/", CityCreateView.as_view(), name="city_create"),
    path("city_update/<int:id>/", CityUpdateView.as_view(), name="city_update"),
    path("city_delete/<int:id>/", CityDeleteView, name="city_delete"),
    path("zone_create/", ZoneCreate.as_view(), name="zone_create"),
    path("zone_update/<int:id>/", ZoneUpdate.as_view(), name="zone_update"),
    path("zone_delete/<int:id>/", ZoneDeleteView, name="zone_delete"),
    path("zone_list/", ZoneListView.as_view(), name="zone_list"),
    path("", ProvinceListView.as_view(), name="province"),
    path("province/create/", ProvinceCreate.as_view(), name="province_create"),
    path("province/update/<int:id>/", ProvinceUpdate.as_view(), name="province_update"),
    path("province/delete/<int:id>/", ProvinceDelete, name="province_delete"),
    path("province/detail/<int:pk>/", ProvinceDetail.as_view(), name="province_detail"),
    # path("city/<int:province>/", CityListView.as_view(), name="city"),
    path("zone/<int:city>/", ZoneListView.as_view(), name="Zone"),
    # path("create/", LocationCreateView.as_view(), name="Create"),
    # path("update/<int:id>/", LocationUpdateView.as_view(), name="update"),
    # path("delete/<int:id>/", LocationDeleteView, name="delete"),
    # path("<str:name>/", City_Of_Province_ListView.as_view(), name="Detail"),
]

location/models.py
from django.db import models
from mptt.models import MPTTModel


class Province(models.Model):
    name = models.CharField(max_length=125)

    def __str__(self):
        return self.name


class City(models.Model):
    name = models.CharField(max_length=50, unique=True)

    province = models.ForeignKey(
        "Province",
        null=True,
        blank=True,
        related_name="children",
        db_index=True,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name


class Zone(models.Model):
    name = models.CharField(max_length=50, unique=True)
    # slug = models.SlugField()
    city = models.ForeignKey(
        "City",
        null=True,
        blank=True,
        related_name="children",
        db_index=True,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.name

location/forms.py
from django import forms

from .models import City, Province, Zone


class LocationForm(forms.ModelForm):
    class Meta:
        model = Zone
        fields = ("name",)

        labels = {
            "name": "منطقه",
        }


class ZoneForm(forms.ModelForm):
    class Meta:
        model = Zone
        fields = ("name", "city")

        labels = {
            "name": "منطقه",
            "city": "شهر",
        }


class ProvinceForm(forms.ModelForm):
    class Meta:
        model = Province
        fields = ("name",)

        labels = {
            "name": "استان",
        }


class CityForm(forms.ModelForm):
    class Meta:
        model = City
        fields = ("name", "province")

        labels = {
            "name": "شهر",
            "province": "استان",
        }

location/views.py
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, DetailView, ListView, UpdateView

from .forms import CityForm, LocationForm, ProvinceForm, ZoneForm
from .models import City, Province, Zone


class ProvinceCreate(CreateView):
    model = Province
    form_class = ProvinceForm
    template_name = "location/province_create.html"
    success_url = reverse_lazy("location:province")


class ProvinceUpdate(UpdateView):
    model = Province
    form_class = ProvinceForm
    template_name = "location/province_update.html"
    success_url = reverse_lazy("location:province")
    slug_field = "id"
    slug_url_kwarg = "id"


class ProvinceListView(ListView):
    model = Province
    template_name = "location/province_list.html"
    context_object_name = "province"


class ProvinceDetail(DetailView):
    def get_queryset(self):
        global province
        province = self.kwargs.get("pk")
        return Province.objects.filter(id=province)

    template_name = "location/city_list.html"
    context_object_name = "province"


def ProvinceDelete(request, id):
    province = get_object_or_404(Province, id=id)
    province.delete()
    return redirect("Location:province")


class CityCreateView(CreateView):
    model = City
    form_class = CityForm
    success_url = reverse_lazy("Location:city_list")
    template_name = "location/city_create.html"


class CityListView(ListView):
    model = City
    template_name = "location/city_lista.html"


class CityUpdateView(UpdateView):
    model = City
    form_class = CityForm
    success_url = reverse_lazy("Location:city_list")
    template_name = "location/update_city.html"
    slug_field = "id"
    slug_url_kwarg = "id"


def CityDeleteView(request, id):
    location = get_object_or_404(City, id=id)
    location.delete()
    return redirect("Location:city_list")


class ZoneListView(ListView):
    model = Zone
    template_name = "location/zone_list.html"


class ZoneCreate(CreateView):
    model = Zone
    form_class = ZoneForm
    template_name = "location/zone_create.html"
    success_url = reverse_lazy("location:zone_list")


class ZoneUpdate(UpdateView):
    model = Zone
    form_class = ZoneForm
    slug_field = "id"
    slug_url_kwarg = "id"
    success_url = reverse_lazy("location:zone_list")
    template_name = "location/zone_update.html"


def ZoneDeleteView(request, id):
    zone = get_object_or_404(Zone, id=id)
    zone.delete()
    return redirect("location:zone_list")

location/templates/location/city_lista.html
{% extends "base.html" %}
{% load static %}
{% block header_static %}
        <!--Morris Chart CSS -->
		<link rel="stylesheet" href="{% static 'config/plugins/morris/morris.css' %}">

        <!-- App css -->
        <link href="{% static 'config/css/bootstrap-rtl.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/core.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/components.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/icons.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/pages.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/menu.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/responsive.css' %}" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <script src="{% static 'config/js/modernizr.min.js' %}"></script>
{% endblock %}
{% block content %}

            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container">

<h1 class="text-center">لیست شهرها</h1>
                        <div class="row">
                            {% for city in object_list %}
                            <div class="col-lg-3 col-md-6">
                        		<div class="card-box">
                        			<h2 class="text-center">{{ city.name }}</h2>
                                    <a href="{% url "location:city_delete" city.id  %}" class="btn btn-danger">حذف</a>
                                    <a href="{% url "location:city_update" city.id %}" class="btn btn-warning">ویرایش</a>
                                    </div>
                        		</div>
                            {% endfor %}
                            </div>
                        </div>
                    </div> <!-- container -->

                </div> <!-- content -->
{% endblock %}
{% block js %}
        <script>
            var resizefunc = [];
        </script>

        <!-- jQuery  -->
        <script src="{% static 'config/js/jquery.min.js' %}"></script>
        <script src="{% static 'config/js/bootstrap-rtl.min.js' %}"></script>
        <script src="{% static 'config/js/detect.js' %}"></script>
        <script src="{% static 'config/js/fastclick.js' %}"></script>
        <script src="{% static 'config/js/jquery.blockUI.js' %}"></script>
        <script src="{% static 'config/js/waves.js' %}"></script>
        <script src="{% static 'config/js/jquery.nicescroll.js' %}"></script>
        <script src="{% static 'config/js/jquery.slimscroll.js' %}"></script>
        <script src="{% static 'config/js/jquery.scrollTo.min.js' %}"></script>

        <!-- KNOB JS -->
        <!--[if IE]>
        <script type="text/javascript" src="{% static 'config/plugins/jquery-knob/excanvas.js' %}"></script>
        <![endif]-->
        <script src="{% static 'config/plugins/jquery-knob/jquery.knob.js' %}"></script>

        <!--Morris Chart-->
		<script src="{% static 'config/plugins/morris/morris.min.js' %}"></script>
		<script src="{% static 'config/plugins/raphael/raphael-min.js' %}"></script>

        <!-- Dashboard init -->
        <script src="{% static 'config/pages/jquery.dashboard.js' %}"></script>

        <!-- App js -->
        <script src="{% static 'config/js/jquery.core.js' %}"></script>
        <script src="{% static 'config/js/jquery.app.js' %}"></script>
{% endblock %}

location/templates/location/province_list.html
{% extends "base.html" %}
{% load static %}
{% block header_static %}
        <!--Morris Chart CSS -->
		<link rel="stylesheet" href="{% static 'config/plugins/morris/morris.css' %}">

        <!-- App css -->
        <link href="{% static 'config/css/bootstrap-rtl.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/core.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/components.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/icons.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/pages.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/menu.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/responsive.css' %}" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <script src="{% static 'config/js/modernizr.min.js' %}"></script>
{% endblock %}
{% block content %}

            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container">

<h1 class="text-center">لیست استان ها</h1>
                        <div class="row">
                            {% for province in object_list %}
                            <div class="col-lg-3 col-md-6">
                        		<div class="card-box">
                                    <a href="{% url "location:province_detail" province.id %}"><h2 class="text-center">{{ province }}</h2></a>
                                    <a href="{% url "location:province_delete" province.id  %}" class="btn btn-danger">حذف</a>
                                    <a href="{% url "location:province_update" province.id %}" class="btn btn-warning">ویرایش</a>
                                    </div>
                        		</div>
                            {% endfor %}
                            </div>
                        </div>
                    </div> <!-- container -->

                </div> <!-- content -->
{% endblock %}
{% block js %}
        <script>
            var resizefunc = [];
        </script>

        <!-- jQuery  -->
        <script src="{% static 'config/js/jquery.min.js' %}"></script>
        <script src="{% static 'config/js/bootstrap-rtl.min.js' %}"></script>
        <script src="{% static 'config/js/detect.js' %}"></script>
        <script src="{% static 'config/js/fastclick.js' %}"></script>
        <script src="{% static 'config/js/jquery.blockUI.js' %}"></script>
        <script src="{% static 'config/js/waves.js' %}"></script>
        <script src="{% static 'config/js/jquery.nicescroll.js' %}"></script>
        <script src="{% static 'config/js/jquery.slimscroll.js' %}"></script>
        <script src="{% static 'config/js/jquery.scrollTo.min.js' %}"></script>

        <!-- KNOB JS -->
        <!--[if IE]>
        <script type="text/javascript" src="{% static 'config/plugins/jquery-knob/excanvas.js' %}"></script>
        <![endif]-->
        <script src="{% static 'config/plugins/jquery-knob/jquery.knob.js' %}"></script>

        <!--Morris Chart-->
		<script src="{% static 'config/plugins/morris/morris.min.js' %}"></script>
		<script src="{% static 'config/plugins/raphael/raphael-min.js' %}"></script>

        <!-- Dashboard init -->
        <script src="{% static 'config/pages/jquery.dashboard.js' %}"></script>

        <!-- App js -->
        <script src="{% static 'config/js/jquery.core.js' %}"></script>
        <script src="{% static 'config/js/jquery.app.js' %}"></script>
{% endblock %}

location/templates/location/zone_list.html
{% extends "base.html" %}
{% load static %}
{% block header_static %}
        <!--Morris Chart CSS -->
		<link rel="stylesheet" href="{% static 'config/plugins/morris/morris.css' %}">

        <!-- App css -->
        <link href="{% static 'config/css/bootstrap-rtl.min.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/core.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/components.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/icons.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/pages.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/menu.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'config/css/responsive.css' %}" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shiv and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <script src="{% static 'config/js/modernizr.min.js' %}"></script>
{% endblock %}
{% block content %}

            <div class="content-page">
                <!-- Start content -->
                <div class="content">
                    <div class="container">

<h1 class="text-center">لیست مناطق</h1>
                        <div class="row">
                            {% for zone in object_list %}
                            <div class="col-lg-3 col-md-6">
                        		<div class="card-box">
                        			<h2 class="text-center">{{ zone.name }}</h2>
                                    <a href="{% url "location:zone_delete" zone.id  %}" class="btn btn-danger">حذف</a>
                                    <a href="{% url "location:zone_update" zone.id %}" class="btn btn-warning">ویرایش</a>
                                    </div>
                        		</div>
                            {% endfor %}
                            </div>
                        </div>
                    </div> <!-- container -->

                </div> <!-- content -->
{% endblock %}
{% block js %}
        <script>
            var resizefunc = [];
        </script>

        <!-- jQuery  -->
        <script src="{% static 'config/js/jquery.min.js' %}"></script>
        <script src="{% static 'config/js/bootstrap-rtl.min.js' %}"></script>
        <script src="{% static 'config/js/detect.js' %}"></script>
        <script src="{% static 'config/js/fastclick.js' %}"></script>
        <script src="{% static 'config/js/jquery.blockUI.js' %}"></script>
        <script src="{% static 'config/js/waves.js' %}"></script>
        <script src="{% static 'config/js/jquery.nicescroll.js' %}"></script>
        <script src="{% static 'config/js/jquery.slimscroll.js' %}"></script>
        <script src="{% static 'config/js/jquery.scrollTo.min.js' %}"></script>

        <!-- KNOB JS -->
        <!--[if IE]>
        <script type="text/javascript" src="{% static 'config/plugins/jquery-knob/excanvas.js' %}"></script>
        <![endif]-->
        <script src="{% static 'config/plugins/jquery-knob/jquery.knob.js' %}"></script>

        <!--Morris Chart-->
		<script src="{% static 'config/plugins/morris/morris.min.js' %}"></script>
		<script src="{% static 'config/plugins/raphael/raphael-min.js' %}"></script>

        <!-- Dashboard init -->
        <script src="{% static 'config/pages/jquery.dashboard.js' %}"></script>

        <!-- App js -->
        <script src="{% static 'config/js/jquery.core.js' %}"></script>
        <script src="{% static 'config/js/jquery.app.js' %}"></script>
{% endblock %}